# Generated by Django 4.0.5 on 2022-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programms',
            name='unico',
            field=models.BooleanField(default=False),
        ),
    ]
