# Generated by Django 4.0.5 on 2022-06-11 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0003_rename_unico_programms_unic'),
    ]

    operations = [
        migrations.AddField(
            model_name='programms',
            name='timeFromFirstMinuteDay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
            preserve_default=False,
        ),
    ]
