# Generated by Django 4.0.5 on 2022-06-14 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0005_rename_timefromfirstminuteday_programms_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='endTime',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)]),
        ),
        migrations.AlterField(
            model_name='programms',
            name='startTime',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
