# Generated by Django 4.0.5 on 2022-06-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0007_programaactual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramaActual',
            new_name='CurrentProgram',
        ),
        migrations.RenameModel(
            old_name='Programms',
            new_name='Programs',
        ),
    ]
