# Generated by Django 4.0.5 on 2022-06-17 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0008_rename_programaactual_currentprogram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='unic',
        ),
        migrations.AlterField(
            model_name='currentprogram',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
